coverage:
  precision: 2
  round: down
  range: 70..100

  status:
    project:
      default:
        target: auto
        threshold: 5 # allow drops by 5 percent
        if_ci_failed: error
    patch:
      default:
        target: auto
        threshold: 0
    changes: false

  ignore:
    - "**/tutorial_material.py"
    - "threeML/test/.*"
    - "threeML/plugins/experimental/.*"
    - "**/__init__.py"
    - "threeML/_version.py"
    - "threeML/minimizer/ROOT_minimizer.py"

comment:
    layout: "condensed_header, condensed_files, condensed_footer"
    behavior: default
