{% set name = "threeml" %}

package:
  name: {{ name }}
  version: {{ os.environ.get('PKG_VERSION') }}

source:
#    git_url: https://github.com/giacomov/3ML.git
  path: ../../../

build:
  script: python -m pip install --no-deps --ignore-installed .
  skip: true  # [win]


requirements:
  
  build:
    # - {{ compiler('c') }}
    # - {{ compiler('cxx') }}
    # - {{ compiler('fortran') }}
    - python
    - numpy>=1.15
    - emcee>=3
    - uncertainties
    - pyyaml>=5.1
    - dill
    - iminuit>=2
    - astromodels>=2
    - astroquery
    - corner>=1.0.2
    - requests
    - speclite
    - multinest # [not arm64]
    - pymultinest # [not arm64]
    - ultranest # [not arm64]
    - dynesty>=1
    - pygmo>=2.4
    - ipywidgets
    - numba
    - ipyparallel
    - py
    - numdifftools
    - interpolation>=2.1.5
    - tqdm>=4.56.0
    - colorama
    - omegaconf
    
  run:
    - python
    - numpy>=1.15
    - scipy>=0.18
    - emcee>=3
    - astropy>=1.0.3
    - matplotlib
    - uncertainties
    - pyyaml>=5.1
    - dill
    - iminuit>=2
    - astromodels>=2.3.8
    - astroquery 
    - corner>=1.0.2
    - pandas>=0.23
    - requests
    - speclite
    - multinest # [not arm64]
    - pymultinest # [not arm64]
    - ultranest # [not arm64]
    - dynesty>=1
    - pygmo>=2.4
    - ipywidgets
    - ipython
    - ipyparallel
    - numba
    - xz
    - py
    - pytest 
    - numexpr
    - numdifftools
    - tqdm>=4.56.0
    - omegaconf
    - asciitree
    - colorama
    - rich

#test:
#  # Python imports
#  commands:
#    - python -c 'import os;os.environ["MPLBACKEND"]="Agg";from threeML import *'


about:
  home: https://github.com/threeML/threeML
  license: BSD-3
  summary: 'The Multi-Mission Maximum Likelihood framework'
  license_family: BSD

extra:
  recipe-maintainers:
    - giacomov
    - ndilalla

