{% set name = "threeml" %}

package:
  name: {{ name }}
  version: {{ os.environ.get('PKG_VERSION') }}

source:
#    git_url: https://github.com/giacomov/3ML.git
  path: ../../../

build:
  script: python -m pip install --no-deps --ignore-installed .
  skip: true  # [win]


requirements:
  
  build:
    # - {{ compiler('c') }}
    # - {{ compiler('cxx') }}
    # - {{ compiler('fortran') }}
    - python
    #- setuptools
    #- toolchain
    - numpy>=1.15
    #- scipy >=0.18
    - emcee>=3
    #- astropy >=1.0.3
    #- matplotlib
    - uncertainties
    - pyyaml>=5.1
    - dill
    - iminuit>=2
    - astromodels>=2
    - astroquery<0.4 # [py2k]
    - astroquery # [py3k]
    - corner>=1.0.2
    #- corner
    #- pandas
    - requests
    - speclite
    - pymultinest
    - ultranest # [py3k]
    - dynesty>=1
    #- pygmo>=2.4,<=2.11.4 # [py2k]
    - pygmo>=2.4
    - ipywidgets
    - numba
    #- ipython
    - ipyparallel
    - py
    #- tk==8.5.19 # [py2k]
    - ipopt<3.13 # [py2k]
    - numdifftools
    - interpolation>=2.1.5 # [py3k]
    - tqdm>=4.56.0
    - colorama
    - omegaconf
    - asciitree
    
  run:
    - python
    - numpy>=1.15 # [py3k]
    - scipy>=0.18
    - emcee>=3
    - astropy>=1.0.3
    - matplotlib
    - uncertainties
    - pyyaml>=5.1
    - dill
    - iminuit>=2
    - astromodels>=2.3.8
    - astroquery<0.4 # [py2k]
    - astroquery # [py3k]
    - corner>=1.0.2
    - pandas>=0.23
    - requests
    - speclite
    - pymultinest
    - ultranest # [py3k]
    - dynesty>=1
    #- pygmo>=2.4,<=2.11.4 # [py2k]
    - pygmo>=2.4
    - ipywidgets
    - ipython
    - ipyparallel
    - numba
    - xz
    - py
    - pytest<4 # [py2k]
    - pytest # [py3k]
    - numexpr
    - ipopt<3.13 # [py2k]
    - numdifftools
    - tqdm>=4.56.0
    - omegaconf
    - asciitree
    - colorama
    - rich

#test:
#  # Python imports
#  commands:
#    - python -c 'import os;os.environ["MPLBACKEND"]="Agg";from threeML import *'


about:
  home: https://github.com/threeML/threeML
  license: BSD-3
  summary: 'The Multi-Mission Maximum Likelihood framework'
  license_family: BSD

extra:
  recipe-maintainers:
    - giacomov
    - ndilalla

