{% set name = "threeml" %}

package:
  name: {{ name }}
  version: {{ os.environ.get('PKG_VERSION') }}

source:
#    git_url: https://github.com/giacomov/3ML.git
  path: ../../../

build:
  script: python -m pip install --no-deps --ignore-installed .
  skip: true  # [win]


requirements:
  
  build:
    # - {{ compiler('c') }}
    # - {{ compiler('cxx') }}
    # - {{ compiler('fortran') }}
    - python
    #- setuptools
    #- toolchain
    - numpy>=1.6,<1.16 # [py<=py35]
    - numpy # [py>py35]
    #- scipy >=0.18
    - emcee>=3
    #- astropy >=1.0.3
    #- matplotlib
    - uncertainties
    - pyyaml==3.13
    - dill
    - iminuit>=1.2
    - astromodels
    - astroquery<0.4 # [py2k]
    - astroquery # [py3k]
    - corner>=1.0.2
    #- pandas
    - requests
    - speclite
    - pymultinest
    - pygmo>=2.4,<=2.11.4 # [py2k]
    - pygmo>=2.4 # [py3k]
    - ipywidgets
    #- ipython
    - ipyparallel
    - py
    - tk==8.5.19 # [py2k]
  
  run:
    - python
    - numpy>=1.6,<1.16 # [py<=py35]
    - numpy # [py>py35]
    - scipy>=0.18
    - emcee>=3
    - astropy>=1.0.3
    - matplotlib
    - uncertainties
    - pyyaml==3.13
    - dill
    - iminuit>=1.2
    - astromodels
    - astroquery<0.4 # [py2k]
    - astroquery # [py3k]
    - corner>=1.0.2
    - pandas>=0.23
    - requests
    - speclite
    - pymultinest
    - pygmo>=2.4,<=2.11.4 # [py2k]
    - pygmo>=2.4 # [py3k]
    - ipywidgets
    - ipython
    - ipyparallel
    - xz
    - py
    - pytest<4 # [py2k]
    - pytest # [py3k]
    - numexpr

#test:
#  # Python imports
#  commands:
#    - python -c 'import os;os.environ["MPLBACKEND"]="Agg";from threeML import *'


about:
  home: https://github.com/threeML/threeML
  license: BSD-3
  summary: 'The Multi-Mission Maximum Likelihood framework'
  license_family: BSD

extra:
  recipe-maintainers:
    - giacomov
    - ndilalla

