{% set name = "threeml" %}

package:
  name: {{ name }}
  version: {{ os.environ.get('PKG_VERSION') }}

source:
  path: ../../

build:
  script: python -m pip install --no-deps --ignore-installed .
  skip: true  # [win]


requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - versioneer
    # Only add numpy here if your build imports code that requires it.
    # - numpy

  run:
    - python
    - numpy
    - scipy >=1.9
    - astropy
    - pandas
    - numexpr
    - numba
    - matplotlib
    - uncertainties
    - tqdm >=4.56.0
    - colorama
    - omegaconf
    - emcee >=3
    - iminuit >=2
    - dynesty >=1
    - astroquery
    - speclite
    - ipywidgets
    - ipyparallel
    - ipython
    - requests
    - dill
    - pyyaml >=5.1
    - corner >=1.0.2
    - numdifftools
    - asciitree
    - rich
    - pip
    - pip:
      - astromodels
    # samplers optionalized below

  run_constrained:
    - multinest        # [not arm64]
    - pymultinest      # [not arm64]
    - ultranest        # [not arm64]

test: # already uses requirements from "run"
  requires:
    - pytest
    - pytest-cov
    - coverage
  source_files:
    - threeML/test
    - threeML/data
    - pyproject.toml # needed for pytest setup e.g. marks
  commands:
    - pytest -vv threeML/test --cov=threeML --cov-report=term

about:
  home: https://github.com/threeML/threeML
  license: BSD-3
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: The Multi-Mission Maximum Likelihood framework
  dev_url: https://github.com/threeML/threeML
  doc_url: https://threeml.readthedocs.io

extra:
  recipe-maintainers:
    - omodei
    - ndilalla

