# base environment file fo CI testing

name: test_env
channels:
  - threeml
  - conda-forge

dependencies:
  - pip
  - pytest
  - pytest-cov
  - astromodels>=2.5.1
  - arviz # needed for autoemcee 
  - codecov
  - coverage
  - setuptools
  - numpy>=1.26
  - scipy>=1.13
  - emcee>=3
  - astropy
  - matplotlib
  - uncertainties
  - pyyaml>=5.1
  - dill
  - iminuit>=2
  - astroquery
  - corner>=1.0.2
  - pandas
  - requests
  - speclite
  - multinest
  - pymultinest
  - ultranest
  - dynesty>=1
  - nautilus-sampler
  - zeus-mcmc
  - ipywidgets
  - ipython
  - ipyparallel
  - numba
  - xz
  - py
  - numexpr
  - ipopt
  - numdifftools
  - tqdm >=4.67.2
  - future
  - colorama
  - omegaconf
  - flake8
  - h5py
  - rich
  - joblib
  - pip:
    - autoemcee
