name: test_env
channels:
  - threeml
  - conda-forge

dependencies:
    - python
    - numpy >=1.26
    - scipy >=1.13
    - emcee >=3.1.5
    - astropy
    - matplotlib
    - uncertainties
    - pyyaml >=5.1
    - dill
    - iminuit >=2.0
    - astromodels >=2.5.1
    - astroquery
    - corner>=1.0.2
    - pandas
    - requests
    - speclite >=0.20
    - ipython
    - ipyparallel
    - joblib
    - numexpr
    - numba
    - numdifftools
    - tqdm >=4.67.2
    - omegaconf
    - rich
    - packaging
    - nautilus-sampler
    - dynesty
    - pip
    - pytest
    - pytest-cov

