context:
  name: threeml 
  version: ${{ git.latest_tag('../')[1:] if git.latest_tag('../') and git.latest_tag('../')[0] == 'v' else git.latest_tag('../') }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  path: ../

build:
  skip: win
  script: pip install . -v

requirements:
  # note that there is no build section
  host:
    - pip
    - python
    - setuptools
    - versioneer

  run:
    - python
    - numpy >=1.26
    - scipy >=1.11
    - emcee >=3
    - astropy
    - matplotlib
    - uncertainties
    - pyyaml >=5.1
    - dill
    - iminuit >=2.0
    - astromodels >=2.5.1
    - astroquery
    - corner>=1.0.2
    - pandas
    - requests
    - speclite >=0.11
    - ipython
    - ipyparallel
    - joblib
    - numexpr
    - numba
    - numdifftools
    - tqdm >=4.56.0
    - omegaconf
    - rich
    - packaging
    - if: (osx and x86_64)
      then: llvmlite<0.46

  run_constraints:
    - if: not (linux and aarch64)
      then: xspec>=12.15.1

tests:
  - python:
      imports:
        - threeML 

  - script:
      - pytest -vv --pyargs threeML
    requirements:
      run:
        - pytest
        - zeus-mcmc
        - dynesty
        - if: not (linux and aarch64)
          then:
          - ultranest
          - pymultinest


about:
  homepage: https://github.com/ipython/ipywidgets
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Jupyter Interactive Widgets
  description: |
    ipywidgets are interactive HTML widgets for Jupyter notebooks and the IPython kernel.
  documentation: https://ipywidgets.readthedocs.io/en/latest/
