# -*- coding: utf-8 -*-
#
# The Multi-Mission Maximum Likelihood framework documentation build configuration file, created by
# sphinx-quickstart on Fri Feb  5 12:26:57 2016.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os
import sys
from pathlib import Path

import mock

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath(".."))
# sys.path.insert(0, os.path.abspath('../threeML/classicMLE'))


DOCS = Path(__file__).parent

# -- Generate API documentation ------------------------------------------------

def run_apidoc(app):
   """Download API stubs from GitHub Actions artifact or generate them locally."""
   import subprocess
   import requests
   import zipfile
   import io
   from pathlib import Path
   
   api_dir = DOCS / "api"
   api_dir.mkdir(exist_ok=True)
   
   # Check if API stubs already exist
   # if list(api_dir.glob("*.rst")):
   #    return  # Already have API stubs
   
   # Try to download from GitHub Actions artifact if GITHUB_TOKEN is available
   github_token = os.environ.get("GITHUB_TOKEN")
   commit_sha = os.environ.get("READTHEDOCS_GIT_COMMIT_HASH") or os.environ.get("READTHEDOCS_VERSION", "")
   
   if github_token and commit_sha and len(commit_sha) == 40:
       # Try to get commit SHA from git if not in environment
       try:
           result = subprocess.run(
               ["git", "rev-parse", "HEAD"],
               capture_output=True,
               text=True,
               cwd=DOCS.parent,
           )
           if result.returncode == 0:
               commit_sha = result.stdout.strip()
       except Exception:
           pass
       
       if commit_sha and len(commit_sha) == 40:
           artifact_name = f"api-stubs-for-{commit_sha}"
           repo = "threeML/threeML"
           
           # Get the workflow run for this commit
           headers = {
               "Authorization": f"token {github_token}",
               "Accept": "application/vnd.github.v3+json"
           }
           url = f"https://api.github.com/repos/{repo}/actions/runs"
           params = {"head_sha": commit_sha, "per_page": 1}
           
           try:
               response = requests.get(url, headers=headers, params=params, timeout=10)
               if response.status_code == 200:
                   runs = response.json().get("workflow_runs", [])
                   if runs:
                       run_id = runs[0]["id"]
                       
                       # Get artifacts for this run
                       artifacts_url = f"https://api.github.com/repos/{repo}/actions/runs/{run_id}/artifacts"
                       response = requests.get(artifacts_url, headers=headers, timeout=10)
                       if response.status_code == 200:
                           artifacts = response.json().get("artifacts", [])
                           api_artifact = next((a for a in artifacts if a["name"] == artifact_name), None)
                           if api_artifact:
                               # Download the artifact
                               download_url = api_artifact["archive_download_url"]
                               response = requests.get(download_url, headers=headers, timeout=30, stream=True)
                               if response.status_code == 200:
                                   zip_data = io.BytesIO(response.content)
                                   with zipfile.ZipFile(zip_data) as zip_file:
                                       zip_file.extractall(api_dir)
                                   print(f"Successfully downloaded API stubs for {commit_sha}")
                                   return  # Successfully downloaded
           except Exception:
               # Fall through to local generation
               print(f"Failed to download API stubs for {commit_sha}")
               pass
   
   # Fallback: generate API stubs locally using sphinx-apidoc
   package_path = DOCS.parent / "threeML"
   output_path = api_dir
   
   # Use sphinx-apidoc command-line tool
   try:
       print(f"Generating API stubs locally using sphinx-apidoc")
       subprocess.run(
           [
               "sphinx-apidoc",
               "--force",
               #"--no-toc",
               #"--separate",
               "-o",
               str(output_path),
               str(package_path),
           ],
           check=True,
           cwd=DOCS.parent,
       )
   except (subprocess.CalledProcessError, FileNotFoundError):
       # If sphinx-apidoc fails or isn't available, that's okay
       # The build will continue without API docs
       raise RuntimeError("Failed to generate API stubs locally using sphinx-apidoc")
       sys.exit(1)


MOCK_MODULES = ["fermipy"]
for mod_name in MOCK_MODULES:
    sys.modules[mod_name] = mock.Mock()


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "nbsphinx",
    "myst_parser",
    "sphinx.ext.autodoc",
    "sphinx.ext.mathjax",
    "sphinx.ext.viewcode",
    "sphinx.ext.githubpages",
    "sphinx.ext.napoleon",
    "sphinx_gallery.load_style",
    "sphinx_rtd_dark_mode",
    "sphinxcontrib.email",
    "sphinx_copybutton",
]

napoleon_google_docstring = True
napoleon_use_param = False


default_dark_mode = True
email_automode = True

if "GITHUB_TOKEN" in os.environ:
    extensions.append("rtds_action")

    # The path where the artifact should be extracted
    # Note: this is relative to the conf.py file!
    rtds_action_path = "notebooks"
    # # The "prefix" used in the `upload-artifact` step of the action
    rtds_action_artifact_prefix = "notebooks-for-"

    rtds_action_github_repo = "threeML/threeML"

    # # A GitHub personal access token is required, more info below
    rtds_action_github_token = os.environ["GITHUB_TOKEN"]

    # For PR builds, don't fail if artifacts aren't ready yet
    # The first automatic build might run before artifacts are ready
    # The webhook-triggered build (after artifacts are ready) will succeed
    # Check if this is a PR build (external version type)
    # is_pr_build = os.environ.get("READTHEDOCS_VERSION_TYPE") == "external"
    # rtds_action_error_if_missing = not is_pr_build
    rtds_action_error_if_missing = True

    # Readthedocs provides the current version/branch name in an environment 
    # variable. For PR builds, we use the PR
    rtds_action_commit_ref = os.environ.get("READTHEDOCS_GIT_COMMIT_HASH")


sphinx_gallery_conf = {
    "default_thumb_file": "media/logo.png"
    #     'matplotlib_animations': True,
    #     'image_srcset': ["2x"],
    #     'nested_sections': False,
    #     'show_api_usage': True,
}


# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = [".rst"]
# source_parsers = {
#     '.md': CommonMarkParser,
# }
# source_suffix = '.rst'

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "The Multi-Mission Maximum Likelihood framework"
copyright = "(2026), the ThreeML developers"
author = "G.Vianello"

# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"


# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ["_build", "**.ipynb_checkpoints"]

html_theme = "sphinx_rtd_dark_mode"


html_theme_options = {
    "logo_only": False,
    "collapse_navigation": True,
    "navigation_depth": 4,
    "prev_next_buttons_location": "bottom",  # top and bottom
}

html_logo = "media/logo.png"
html_show_sourcelink = False
html_favicon = "media/favicon.ico"

autosectionlabel_prefix_document = True

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------


# Output file base name for HTML help builder.
htmlhelp_basename = "TheMulti-MissionMaximumLikelihoodframeworkdoc"
html_baseurl = ""

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    # 'preamble': '',
    # Latex figure (float) alignment
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "TheMulti-MissionMaximumLikelihoodframework.tex",
        "The Multi-Mission Maximum Likelihood framework Documentation",
        "G.Vianello",
        "manual",
    ),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
# latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
# latex_use_parts = False

# If true, show page references after internal links.
# latex_show_pagerefs = False

# If true, show URL addresses after external links.
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
# latex_appendices = []

# If false, no module index is generated.
# latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (
        master_doc,
        "themulti-missionmaximumlikelihoodframework",
        "The Multi-Mission Maximum Likelihood framework Documentation",
        [author],
        1,
    )
]

# If true, show URL addresses after external links.
# man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "TheMulti-MissionMaximumLikelihoodframework",
        "The Multi-Mission Maximum Likelihood framework Documentation",
        author,
        "TheMulti-MissionMaximumLikelihoodframework",
        "One line description of project.",
        "Miscellaneous",
    ),
]


def setup(app):
    app.connect("builder-inited", run_apidoc)
