name: Conda Build and Publish
on:
    push:
      paths-ignore:
        - "README.md"
        - "**/docs/**"
        - ".github/workflows/docs.yml"
      branches:
        - master
        - dev
      tags:
        - "v*"
    pull_request:
      branches:
        - master
        - dev
    schedule:
        - cron: "0 11 * * 1"

jobs:
    build-conda:
        name: Build and verify with Conda
        if: startsWith(github.ref, 'refs/tags') == false
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
              include:
                - os: ubuntu-latest
                  target-platform: linux-64
                - os: macos-latest
                  target-platform: osx-arm64
                - os: ubuntu-24.04-arm
                  target-platform: linux-aarch64
                - os: macos-15-intel
                  target-platform: osx-64
        steps:
            - name: Checkout
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: Setup rattler-build 
              uses: prefix-dev/rattler-build-action@v0.2.37
              with:
                upload-artifact: false
                setup-only: true
                artifact-name: threeml-${{ matrix.target-platform }}

            - name: Build package
              run: |

                  echo "Running on development branch: ${ISDEV} "
                
                  if [[ "${ISDEV}" == "true" ]]; then
                    rattler-build build --target-platform ${{ matrix.target-platform }} -c threeML/label/dev -c conda-forge --recipe conda-dist/recipe.yaml --experimental
                  else
                    rattler-build build --target-platform ${{ matrix.target-platform }} -c threeML -c conda-forge --recipe conda-dist/recipe.yaml --experimental
                  fi
              env:
                  ISDEV: ${{contains(github.ref, 'dev') || contains(github.base_ref, 'dev')}}
                  OMP_NUM_THREADS: 1
                  MKL_NUM_THREADS: 1
                  NUMEXPR_NUM_THREADS: 1
                  MPLBACKEND: "Agg"

    publish-conda:
        name: Publish to Conda
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
              include:
                - os: ubuntu-latest
                  target-platform: linux-64
                - os: macos-latest
                  target-platform: osx-arm64
                - os: ubuntu-24.04-arm
                  target-platform: linux-aarch64
                - os: macos-15-intel
                  target-platform: osx-64
        steps:
            - name: Checkout
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0
            - name: Setup rattler-build 
              uses: prefix-dev/rattler-build-action@v0.2.37
              with:
                upload-artifact: false
                setup-only: true

            - name: Build package
              run: |
                if [[ "${ISDEV}" == "true" ]]; then
                  rattler-build build --target-platform ${{ matrix.target-platform }} -c threeML/label/dev -c conda-forge --recipe conda-dist/recipe.yaml --experimental
                else
                  rattler-build build --target-platform ${{ matrix.target-platform }} -c threeML -c conda-forge --recipe conda-dist/recipe.yaml --experimental
                fi

                echo "Uploading ${{matrix.os}} IsDev: ${ISDEV} "
                if [[ "${ISDEV}" == "true" ]]; then
                  LABEL="--channel dev"
                fi

                rattler-build upload anaconda ${CONDA_BLD_PATH}/${{ matrix.target-platform }}/*.conda --force --owner threeml ${LABEL}

              env:
                  OMP_NUM_THREADS: 1
                  MKL_NUM_THREADS: 1
                  NUMEXPR_NUM_THREADS: 1
                  MPLBACKEND: "Agg"
                  ANACONDA_API_KEY: ${{secrets.CONDA_TOKEN}}
                  ISDEV: ${{contains(github.ref, 'dev')}}



