name: Close stale issues and PRs
on:
  schedule:
  - cron: 30 1 * * *

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has become stale. Is there an update? We will close in 15 days'
        stale-pr-message: 'This PR has become stale. We will close in 60 days'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-pr-stale: 90
        days-before-issue-stale: 30
        days-before-issue-close: 15
        days-before-pr-close: 60

